extends Node

#GRUPOS
const GRUPO_INIMIGO = "000000"
const GRUPO_ALIADOS = "000001"
const GRUPO_CURSOR_MOUSE = "000002"


#TIPOS DE DANO

const TIPO_DE_DANO_CONTUSIVO=0
const TIPO_DE_DANO_CORTANTE=1
const TIPO_DE_DANO_PERFURANTE=2
const TIPO_DE_DANO_IMATERIAL=3

#RAÇA

const RACA_HUMANO=10
const RACA_GOBLIN=11
const RACA_ELFO=12
const RACA_GNOMO=13
const RACA_ANAO=14
const RACA_ORC=15
const RACA_FADA=16
const RACA_TROLL=17

#GRUPO RAÇA

const GRUPO_RACA_HUMANOIDE=100
const GRUPO_RACA_FERA=101
const GRUPO_RACA_PEIXE=102
const GRUPO_RACA_AVE=103
const GRUPO_RACA_ELEMENTAL=104
const GRUPO_RACA_DRAGAO=105
const GRUPO_RACA_MORTO_VIVO=106
const GRUPO_RACA_DEMONIO=107
const GRUPO_RACA_GOLEN=108
const GRUPO_RACA_PLANTA=109


#PROPRIEDADE DO ATAQUE

const PROPRIEDADE_DO_ATAQUE_NEUTRO=20 # FRACO FANTASMA 
const PROPRIEDADE_DO_ATAQUE_AGUA=22 # FRACO CONTRA RAIO e FRACO CONTRA TERRA | RESISTENCIA A GELO 
const PROPRIEDADE_DO_ATAQUE_RAIO=23 # FRACO CONTRA TERRA e FRACO CONTRA PLANTA | RESISTENCIA A AGUA
const PROPRIEDADE_DO_ATAQUE_TERRA=24 # FRACO CONTRA PLANTA e FRACO CONTRA FOGO | RESISTENCIA A RAIO
const PROPRIEDADE_DO_ATAQUE_PLANTA=25 # FRACO CONTRA FOGO e FRACO CONTRA RAIO | RESISTENCIA A TERRA
const PROPRIEDADE_DO_ATAQUE_FOGO=21 # FRACO CONTRA VENTO e FRACO CONTRA GELO  | RESISTENCIA A PLANTA
const PROPRIEDADE_DO_ATAQUE_VENTO=26 # FRACO CONTRA GELO e FRACO CONTRA AGUA  | RESISTENCIA A FOGO
const PROPRIEDADE_DO_ATAQUE_GELO=27 #FRACO CONTRA AGUA  e FRACO CONTRA FOGO | RESISTENCIA A VENTO
const PROPRIEDADE_DO_ATAQUE_MALIGNO=28 #FRACO CONTRA SAGRADO
const PROPRIEDADE_DO_ATAQUE_SAGRADO=29 #FRACO CONTRA FANTASMA
const PROPRIEDADE_DO_ATAQUE_FANTASMA=30 #FRACO CONTRA SAGRADO e FRACO CONTRA MALIGNO | RESISTENCIA A NEUTRO



#ATAQUES

const ATAQUE_BASICO_FISICO_CORPO_A_CORPO=1000
const ATAQUE_BASICO_FISICO_DISTANCIA=1001
const ATAQUE_BASICO_MAGICO_CORPO_A_CORPO=1002
const ATAQUE_BASICO_MAGICO_DISTANCIA=1003
const ATAQUE_AAA=1004

